build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
